### PR TITLE
Simplify the computation of graadient estimate

### PR DESCRIPTION
**Pull request by tarokiritani**
The gradients for all axes in a minibatch were averaged, and then
multiplied by the mini-batch size. This is simplified with just a
summation.

### CODE REVIEW

**Comment by feinsteinben** [comment]
@tarokiritani I have added a `reduction` option. my concern is that sometimes this function will be used to directly approximate the gradient, so I don't want to have side effects on the signature of `spsa_grad`. Maybe a better solution will be to move the mini-batches summation into this function. what do you think about it?

**Comment by tarokiritani** [comment]
@feinsteinben I agree that there should be a function that just returns the estimate of gradient. Containing the summation (and averaging) of mini-batches into spsa_grad() should simplify the code, and makes sense.

**Comment by tarokiritani** [comment]
@feinsteinben If you have not worked on this, I am interested in doing it by extending my effort in #5 .

**Comment by feinsteinben** [comment]
@tarokiritani closed this PR as it was implemented.

**Pull request closed without merging**
