### PR TITLE
Fix the clamp of perturbation

### PR DESCRIPTION
**Pull request by tarokiritani**
Possibly a serious bug.

### CODE REVIEW

**Comment by tarokiritani** [comment]
Wait. Im a bit confused. Maybe I am mistaken?

**Comment by tarokiritani** [comment]
Silly me. I overlooked `+` in `+=`. I suggest `dx = x_adv - x` might be easier to understand, at least to me. It would be slightly faster too.

**Comment by tarokiritani** [comment]
I realized why you had done this, and why my suggestion does not work.. The optimizer needs to keep track of `dx`. My bad.

**Comment by feinsteinben** [comment]
exactly. I'll add a comment to explain that.

**Pull request closed without merging**
